name: portfolio
description: My personal portofolio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.7
  gap: ^3.0.1
  flutter_custom_clippers: ^2.1.0
  font_awesome_flutter: ^10.6.0
  icons_plus: ^5.0.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/country_flags/
  uses-material-design: true