name: portfolio
description: My personal portofolio describing me.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.1.7
  wave: ^0.2.2
  get: ^4.6.6
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_custom_clippers: ^2.1.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/images/country_flags/
  uses-material-design: true